### ISSUE TITLE
Deps upgrade

### ISSUE THREAD

**Issue by rusudinu** [alepop/dart-ed25519-hd-key#15]
pinenacl needs to be updated to 0.6.0 otherwise on newer flutter versions the following error will occur at build:
![image](https://github.com/user-attachments/assets/1d222061-deb7-44d4-9168-a56832ede393)

**Comment by alepop** [comment]
@rusudinu new version of package have been published ([2.3.0](https://pub.dev/packages/ed25519_hd_key/versions/2.3.0))
