### ISSUE TITLE
plz, null-safety

### ISSUE THREAD

**Issue by ttb-inc** [alepop/dart-ed25519-hd-key#2]
Please update null-safety.
Can you tell me when the update will be available?
Thank you.

**Comment by alepop** [comment]
I will make it soon

**Comment by ttb-inc** [comment]
https://github.com/ethers-io/ethers.js/blob/master/packages/hdnode/src.ts/index.ts

Thank you.

**Comment by alepop** [comment]
@ttb-inc new version published
