### ISSUE TITLE
derivePath invalid

### ISSUE THREAD

**Issue by Hanggi** [alepop/dart-ed25519-hd-key#4]
```
KeyData data = await ED25519_HD_KEY.derivePath("m/44'/60'/0'/0/0", seedBytes);
```

The code above shows errors like:

```
E/flutter (18244): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Invalid number (at character 1)
E/flutter (18244): 
E/flutter (18244): ^
E/flutter (18244): 
E/flutter (18244): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:129:7)
E/flutter (18244): #1      int.parse (dart:core-patch/integers_patch.dart:53:14)
```

any helps? thank you.

**Comment by alepop** [comment]
@Hanggi non-hardened derivation paths are not possible for **ed25519**. It's based on spec [slip-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md). You should change your code to this
`
KeyData data = await ED25519_HD_KEY.derivePath("m/44'/60'/0'/0'/0'", seedBytes);
`
