### ISSUE TITLE
Receive curve as parameter?

### ISSUE THREAD

**Issue by allanclempe** [alepop/dart-ed25519-hd-key#5]
Hi there,

I've been using this library on my flutter wallet but someone came across [this issue](https://github.com/allanclempe/ether-wallet-flutter/issues/7#issuecomment-631435104) a while ago. At that time I did [copy your code](https://github.com/allanclempe/ether-wallet-flutter/blob/master/lib/utils/hd_key.dart) to fix the issue and match the secret with the original [hdkey js library](https://github.com/cryptocoinjs/hdkey/blob/master/lib/hdkey.js#L7). So now, I had to update some of my libraries (including this) and don't want to maintain the code there as well.

What do you think of receiving the secret (curve) as a optional parameter?

Thanks.

**Comment by alepop** [comment]
Hi @allanclempe.

Thank you for opening issue. It's strange for me that eth don't use standard bip for generating hd keys. Anyway I'm not against passing `master secret` for curved bytes as an optional parameter. Feel free to make a pull request. 
New tests for this feature with original test vectors would be great also.

Thanks.

**Comment by alepop** [comment]
@allanclempe version `2.1.0` published.
