### ISSUE TITLE
cannot generate private key from derive path

### ISSUE THREAD

**Issue by mayank-sol** [alepop/dart-ed25519-hd-key#9]
I am trying to generate private key from derive hd path **"m/44'/60'/0'/0"** , but it is giving me errors 

`dart:core                                     int.parse
package:ed25519_hd_key/src/hd_key.dart 34:23  _ED25519HD.derivePath

FormatException: Invalid number (at character 1)`

My implementation is below:

`final seed = bip39.mnemonicToSeedHex(mnemonic);
    final master = await ED25519_HD_KEY.derivePath("m/44'/60'/0'/0", hex.decode(seed));`

As of my inspection find out that this line of code at line 34 in hd_key.dart is causing the error for the last digit 0 in HD path.

`int index = int.parse(segment.substring(0, segment.length - 1));`

I am sure this is a correct HD path as already using it with web3js implementation.

**Comment by alepop** [comment]
@mayank-sol hey! Last `0` digit should also be with `'` sign. Correct path for ed25519 should be `m/44'/60'/0'/0'`

**Comment by mayank-sol** [comment]
Hi @alepop , last digit with `'` sign is working, but I have an another issue, will try to explain below if you can help me

We are migrating from a Javascript based Web3 wallet to Flutter using dart packages, and

`Address generated from mnemonic is different what seems to generated using web3 Javascript library`

I am using web3Dart package to generate the public address using the private key generated in previous step.

```import 'package:bip39/bip39.dart' as bip39;
import 'package:ed25519_hd_key/ed25519_hd_key.dart';
import 'package:hex/hex.dart';
import 'package:convert/convert.dart';
import 'package:web3dart/credentials.dart';

Future<String> getPrivateKey(String mnemonic) async {
    final seed = bip39.mnemonicToSeedHex(mnemonic);
    final master = await ED25519_HD_KEY.derivePath("m/44'/60'/0'/0'", hex.decode(seed));
    final privateKey = HEX.encode(master.key);
    print('private: $privateKey');
    return privateKey;
  }

Future<EthereumAddress> getPublicAddress(String privateKey) async {
    final private = EthPrivateKey.fromHex(privateKey);

    final address = await private.extractAddress();
    print('address: $address');
    return address;
  }```

although this is working, public address is generated but the problem is it is not equals to the my previous Javascript wallet.

**Comment by alepop** [comment]
@mayank-sol sorry I can't help you with your problem. You should check how generation of address is working on your previous js implementation and with dart web3Dart. But you can be sure that this library work fine, because for tests cases it uses original test vectors from [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md)
